# schema = "https://raw.githubusercontent.com/project-gauntlet/gauntlet/refs/heads/main/docs/schema/plugin_manifest.schema.json"

[gauntlet]
name = 'Same Old Plugins'
description = """
sameoldlab's Plugin Repo
"""

# [[authors.sameoldlab]]
# name = "sameoldlab"
# uris = ["https://gtihub.com/sameoldlab"]


[[entrypoint]]
type = 'view'
id = 'windows'
name = 'Windows'
path = 'src/windows.tsx'
description = 'Wayland window tracking'

[permissions.exec]
command = ["pop-launcher"]

[[supported_system]]
os = 'linux'
