[gauntlet]
name = 'Same Old Plugins'
description = """
sameoldlab's Plugin Repo
"""

[[entrypoint]]
id = 'template-view'
name = 'Template view'
path = 'src/template-view/index.tsx'
type = 'view'
description = """
Template Plugin Entrypoint Description
"""
