# schema = "https://raw.githubusercontent.com/project-gauntlet/gauntlet/refs/heads/main/docs/schema/plugin_manifest.schema.json"

[gauntlet]
name = 'Same Old Plugins'
description = """
sameoldlab's Plugin Repo
"""

# [[authors.sameoldlab]]
# name = "sameoldlab"
# uris = ["https://gtihub.com/sameoldlab"]


[[entrypoint]]
id = 'template-view'
name = 'Template view'
path = 'src/template-view/index.tsx'
type = 'view'
description = """
Template Plugin Entrypoint Description
"""

[permissions.exec]
command = ["pop-launcher"]

[[supported_system]]
os = 'linux'
