# schema = "https://raw.githubusercontent.com/project-gauntlet/gauntlet/refs/heads/main/docs/schema/plugin_manifest.schema.json"

[gauntlet]
name = 'Same Old Plugins'
description = "sameoldlab's Plugin Repo"

[[entrypoint]]
id = 'windows'
name = 'Windows'
path = 'src/windows.tsx'
type = 'view'
description = 'Wayland window tracking'

[[entrypoint]]
id = 'find'
name = 'Find'
path = 'src/find.tsx'
type = 'view'
description = 'Search files'

[permissions.exec]
command = ["pop-launcher", "wlrctl","file", "xdg-open", "goldfish"]

[permissions.filesystem]
read = ["/"]

[[supported_system]]
os = 'linux'
