# schema = "https://raw.githubusercontent.com/project-gauntlet/gauntlet/refs/heads/main/docs/schema/plugin_manifest.schema.json"

[gauntlet]
name = 'Same Old Plugins'
description = "sameoldlab's Plugin Repo"

[[entrypoint]]
id = 'windows'
name = 'Windows'
path = 'src/windows.tsx'
type = 'view'
description = 'Wayland window tracking'

[permissions.exec]
command = ["pop-launcher", "wlrctl"]

[[supported_system]]
os = 'linux'
